global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: kminion
    static_configs:
      - targets: ["kminion:8080"]
  - job_name: clickhouse
    static_configs:
      - targets: ["clickhouse:9363"]
  - job_name: edr_snapshot
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets: ["metrics-snapshot:9400"]
